services:
  database:
    image: mysql
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    volumes:
      - ./backups:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=b4$$hcr4$$h3rs
      - MYSQL_DATABASE=musica
  app:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    ports:
      - 4040:80
  pma:
    image: phpmyadmin
    restart: unless-stopped
    volumes:
      - ../pma/pma.conf:/etc/apache2/conf-enabled/pma.conf
      - ../pma/.htaccess:/var/www/html/.htaccess
      - ../pma/.htpasswd:/etc/phpmyadmin/.htpasswd
    ports:
      - 4041:80
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=b4$$hcr4$$h3rs