services:
  database:
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=musica
  app:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - ${APP_EXPOSE}:80