services:
  database:
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_spanish_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./backups:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASS}
      - MYSQL_DATABASE=musica
  app:
    depends_on:
      - database
    build: .
    restart: unless-stopped
    env_file:
      - ../.env.production
    ports:
      - ${APP_EXPOSE}:80
  pma:
    volumes:
      - ../pma/pma.conf:/etc/apache2/conf-enabled/pma.conf
      - ../pma/.htaccess:/var/www/html/.htaccess
      - ../pma/.htpasswd:/etc/phpmyadmin/.htpasswd
    ports:
      - ${PMA_PORT}:80
    restart: always
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=${DATABASE_PASS}