"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    queryInterface.bulkInsert("paises", [
      { id: 1, Nombre_Corto: "AF", Nombre: "Afganistán" },
      { id: 2, Nombre_Corto: "AX", Nombre: "Islas Gland" },
      { id: 3, Nombre_Corto: "AL", Nombre: "Albania" },
      { id: 4, Nombre_Corto: "DE", Nombre: "Alemania" },
      { id: 5, Nombre_Corto: "AD", Nombre: "Andorra" },
      { id: 6, Nombre_Corto: "AO", Nombre: "Angola" },
      { id: 7, Nombre_Corto: "AI", Nombre: "Anguilla" },
      { id: 8, Nombre_Corto: "AQ", Nombre: "Antártida" },
      { id: 9, Nombre_Corto: "AG", Nombre: "Antigua y Barbuda" },
      { id: 10, Nombre_Corto: "AN", Nombre: "Antillas Holandesas" },
      { id: 11, Nombre_Corto: "SA", Nombre: "Arabia Saudí" },
      { id: 12, Nombre_Corto: "DZ", Nombre: "Argelia" },
      { id: 13, Nombre_Corto: "AR", Nombre: "Argentina" },
      { id: 14, Nombre_Corto: "AM", Nombre: "Armenia" },
      { id: 15, Nombre_Corto: "AW", Nombre: "Aruba" },
      { id: 16, Nombre_Corto: "AU", Nombre: "Australia" },
      { id: 17, Nombre_Corto: "AT", Nombre: "Austria" },
      { id: 18, Nombre_Corto: "AZ", Nombre: "Azerbaiyán" },
      { id: 19, Nombre_Corto: "BS", Nombre: "Bahamas" },
      { id: 20, Nombre_Corto: "BH", Nombre: "Bahréin" },
      { id: 21, Nombre_Corto: "BD", Nombre: "Bangladesh" },
      { id: 22, Nombre_Corto: "BB", Nombre: "Barbados" },
      { id: 23, Nombre_Corto: "BY", Nombre: "Bielorrusia" },
      { id: 24, Nombre_Corto: "BE", Nombre: "Bélgica" },
      { id: 25, Nombre_Corto: "BZ", Nombre: "Belice" },
      { id: 26, Nombre_Corto: "BJ", Nombre: "Benin" },
      { id: 27, Nombre_Corto: "BM", Nombre: "Bermudas" },
      { id: 28, Nombre_Corto: "BT", Nombre: "Bhután" },
      { id: 29, Nombre_Corto: "BO", Nombre: "Bolivia" },
      { id: 30, Nombre_Corto: "BA", Nombre: "Bosnia y Herzegovina" },
      { id: 31, Nombre_Corto: "BW", Nombre: "Botsuana" },
      { id: 32, Nombre_Corto: "BV", Nombre: "Isla Bouvet" },
      { id: 33, Nombre_Corto: "BR", Nombre: "Brasil" },
      { id: 34, Nombre_Corto: "BN", Nombre: "Brunéi" },
      { id: 35, Nombre_Corto: "BG", Nombre: "Bulgaria" },
      { id: 36, Nombre_Corto: "BF", Nombre: "Burkina Faso" },
      { id: 37, Nombre_Corto: "BI", Nombre: "Burundi" },
      { id: 38, Nombre_Corto: "CV", Nombre: "Cabo Verde" },
      { id: 39, Nombre_Corto: "KY", Nombre: "Islas Caimán" },
      { id: 40, Nombre_Corto: "KH", Nombre: "Camboya" },
      { id: 41, Nombre_Corto: "CM", Nombre: "Camerún" },
      { id: 42, Nombre_Corto: "CA", Nombre: "Canadá" },
      { id: 43, Nombre_Corto: "CF", Nombre: "República Centroafricana" },
      { id: 44, Nombre_Corto: "TD", Nombre: "Chad" },
      { id: 45, Nombre_Corto: "CZ", Nombre: "República Checa" },
      { id: 46, Nombre_Corto: "CL", Nombre: "Chile" },
      { id: 47, Nombre_Corto: "CN", Nombre: "China" },
      { id: 48, Nombre_Corto: "CY", Nombre: "Chipre" },
      { id: 49, Nombre_Corto: "CX", Nombre: "Isla de Navidad" },
      { id: 50, Nombre_Corto: "VA", Nombre: "Ciudad del Vaticano" },
      { id: 51, Nombre_Corto: "CC", Nombre: "Islas Cocos" },
      { id: 52, Nombre_Corto: "CO", Nombre: "Colombia" },
      { id: 53, Nombre_Corto: "KM", Nombre: "Comoras" },
      { id: 54, Nombre_Corto: "CD", Nombre: "República Democrática del Congo" },
      { id: 55, Nombre_Corto: "CG", Nombre: "Congo" },
      { id: 56, Nombre_Corto: "CK", Nombre: "Islas Cook" },
      { id: 57, Nombre_Corto: "KP", Nombre: "Corea del Norte" },
      { id: 58, Nombre_Corto: "KR", Nombre: "Corea del Sur" },
      { id: 59, Nombre_Corto: "CI", Nombre: "Costa de Marfil" },
      { id: 60, Nombre_Corto: "CR", Nombre: "Costa Rica" },
      { id: 61, Nombre_Corto: "HR", Nombre: "Croacia" },
      { id: 62, Nombre_Corto: "CU", Nombre: "Cuba" },
      { id: 63, Nombre_Corto: "DK", Nombre: "Dinamarca" },
      { id: 64, Nombre_Corto: "DM", Nombre: "Dominica" },
      { id: 65, Nombre_Corto: "DO", Nombre: "República Dominicana" },
      { id: 66, Nombre_Corto: "EC", Nombre: "Ecuador" },
      { id: 67, Nombre_Corto: "EG", Nombre: "Egipto" },
      { id: 68, Nombre_Corto: "SV", Nombre: "El Salvador" },
      { id: 69, Nombre_Corto: "AE", Nombre: "Emiratos Árabes Unidos" },
      { id: 70, Nombre_Corto: "ER", Nombre: "Eritrea" },
      { id: 71, Nombre_Corto: "SK", Nombre: "Eslovaquia" },
      { id: 72, Nombre_Corto: "SI", Nombre: "Eslovenia" },
      { id: 73, Nombre_Corto: "ES", Nombre: "España" },
      {
        id: 74,
        Nombre_Corto: "UM",
        Nombre: "Islas ultramarinas de Estados Unido",
      },
      { id: 75, Nombre_Corto: "US", Nombre: "Estados Unidos" },
      { id: 76, Nombre_Corto: "EE", Nombre: "Estonia" },
      { id: 77, Nombre_Corto: "ET", Nombre: "Etiopía" },
      { id: 78, Nombre_Corto: "FO", Nombre: "Islas Feroe" },
      { id: 79, Nombre_Corto: "PH", Nombre: "Filipinas" },
      { id: 80, Nombre_Corto: "FI", Nombre: "Finlandia" },
      { id: 81, Nombre_Corto: "FJ", Nombre: "Fiyi" },
      { id: 82, Nombre_Corto: "FR", Nombre: "Francia" },
      { id: 83, Nombre_Corto: "GA", Nombre: "Gabón" },
      { id: 84, Nombre_Corto: "GM", Nombre: "Gambia" },
      { id: 85, Nombre_Corto: "GE", Nombre: "Georgia" },
      {
        id: 86,
        Nombre_Corto: "GS",
        Nombre: "Islas Georgias del Sur y Sandwich dl Sur",
      },
      { id: 87, Nombre_Corto: "GH", Nombre: "Ghana" },
      { id: 88, Nombre_Corto: "GI", Nombre: "Gibraltar" },
      { id: 89, Nombre_Corto: "GD", Nombre: "Granada" },
      { id: 90, Nombre_Corto: "GR", Nombre: "Grecia" },
      { id: 91, Nombre_Corto: "GL", Nombre: "Groenlandia" },
      { id: 92, Nombre_Corto: "GP", Nombre: "Guadalupe" },
      { id: 93, Nombre_Corto: "GU", Nombre: "Guam" },
      { id: 94, Nombre_Corto: "GT", Nombre: "Guatemala" },
      { id: 95, Nombre_Corto: "GF", Nombre: "Guayana Francesa" },
      { id: 96, Nombre_Corto: "GN", Nombre: "Guinea" },
      { id: 97, Nombre_Corto: "GQ", Nombre: "Guinea Ecuatorial" },
      { id: 98, Nombre_Corto: "GW", Nombre: "Guinea-Bissau" },
      { id: 99, Nombre_Corto: "GY", Nombre: "Guyana" },
      { id: 100, Nombre_Corto: "HT", Nombre: "Haití" },
      { id: 101, Nombre_Corto: "HM", Nombre: "Islas Heard y McDonald" },
      { id: 102, Nombre_Corto: "HN", Nombre: "Honduras" },
      { id: 103, Nombre_Corto: "HK", Nombre: "Hong Kong" },
      { id: 104, Nombre_Corto: "HU", Nombre: "Hungría" },
      { id: 105, Nombre_Corto: "IN", Nombre: "India" },
      { id: 106, Nombre_Corto: "ID", Nombre: "Indonesia" },
      { id: 107, Nombre_Corto: "IR", Nombre: "Irán" },
      { id: 108, Nombre_Corto: "IQ", Nombre: "Iraq" },
      { id: 109, Nombre_Corto: "IE", Nombre: "Irlanda" },
      { id: 110, Nombre_Corto: "IS", Nombre: "Islandia" },
      { id: 111, Nombre_Corto: "IL", Nombre: "Israel" },
      { id: 112, Nombre_Corto: "IT", Nombre: "Italia" },
      { id: 113, Nombre_Corto: "JM", Nombre: "Jamaica" },
      { id: 114, Nombre_Corto: "JP", Nombre: "Japón" },
      { id: 115, Nombre_Corto: "JO", Nombre: "Jordania" },
      { id: 116, Nombre_Corto: "KZ", Nombre: "Kazajstán" },
      { id: 117, Nombre_Corto: "KE", Nombre: "Kenia" },
      { id: 118, Nombre_Corto: "KG", Nombre: "Kirguistán" },
      { id: 119, Nombre_Corto: "KI", Nombre: "Kiribati" },
      { id: 120, Nombre_Corto: "KW", Nombre: "Kuwait" },
      { id: 121, Nombre_Corto: "LA", Nombre: "Laos" },
      { id: 122, Nombre_Corto: "LS", Nombre: "Lesotho" },
      { id: 123, Nombre_Corto: "LV", Nombre: "Letonia" },
      { id: 124, Nombre_Corto: "LB", Nombre: "Líbano" },
      { id: 125, Nombre_Corto: "LR", Nombre: "Liberia" },
      { id: 126, Nombre_Corto: "LY", Nombre: "Libia" },
      { id: 127, Nombre_Corto: "LI", Nombre: "Liechtenstein" },
      { id: 128, Nombre_Corto: "LT", Nombre: "Lituania" },
      { id: 129, Nombre_Corto: "LU", Nombre: "Luxemburgo" },
      { id: 130, Nombre_Corto: "MO", Nombre: "Macao" },
      { id: 131, Nombre_Corto: "MK", Nombre: "ARY Macedonia" },
      { id: 132, Nombre_Corto: "MG", Nombre: "Madagascar" },
      { id: 133, Nombre_Corto: "MY", Nombre: "Malasia" },
      { id: 134, Nombre_Corto: "MW", Nombre: "Malawi" },
      { id: 135, Nombre_Corto: "MV", Nombre: "Maldivas" },
      { id: 136, Nombre_Corto: "ML", Nombre: "Malí" },
      { id: 137, Nombre_Corto: "MT", Nombre: "Malta" },
      { id: 138, Nombre_Corto: "FK", Nombre: "Islas Malvinas" },
      { id: 139, Nombre_Corto: "MP", Nombre: "Islas Marianas del Norte" },
      { id: 140, Nombre_Corto: "MA", Nombre: "Marruecos" },
      { id: 141, Nombre_Corto: "MH", Nombre: "Islas Marshall" },
      { id: 142, Nombre_Corto: "MQ", Nombre: "Martinica" },
      { id: 143, Nombre_Corto: "MU", Nombre: "Mauricio" },
      { id: 144, Nombre_Corto: "MR", Nombre: "Mauritania" },
      { id: 145, Nombre_Corto: "YT", Nombre: "Mayotte" },
      { id: 146, Nombre_Corto: "MX", Nombre: "México" },
      { id: 147, Nombre_Corto: "FM", Nombre: "Micronesia" },
      { id: 148, Nombre_Corto: "MD", Nombre: "Moldavia" },
      { id: 149, Nombre_Corto: "MC", Nombre: "Mónaco" },
      { id: 150, Nombre_Corto: "MN", Nombre: "Mongolia" },
      { id: 151, Nombre_Corto: "MS", Nombre: "Montserrat" },
      { id: 152, Nombre_Corto: "MZ", Nombre: "Mozambique" },
      { id: 153, Nombre_Corto: "MM", Nombre: "Myanmar" },
      { id: 154, Nombre_Corto: "NA", Nombre: "Namibia" },
      { id: 155, Nombre_Corto: "NR", Nombre: "Nauru" },
      { id: 156, Nombre_Corto: "NP", Nombre: "Nepal" },
      { id: 157, Nombre_Corto: "NI", Nombre: "Nicaragua" },
      { id: 158, Nombre_Corto: "NE", Nombre: "Níger" },
      { id: 159, Nombre_Corto: "NG", Nombre: "Nigeria" },
      { id: 160, Nombre_Corto: "NU", Nombre: "Niue" },
      { id: 161, Nombre_Corto: "NF", Nombre: "Isla Norfolk" },
      { id: 162, Nombre_Corto: "NO", Nombre: "Noruega" },
      { id: 163, Nombre_Corto: "NC", Nombre: "Nueva Caledonia" },
      { id: 164, Nombre_Corto: "NZ", Nombre: "Nueva Zelanda" },
      { id: 165, Nombre_Corto: "OM", Nombre: "Omán" },
      { id: 166, Nombre_Corto: "NL", Nombre: "Países Bajos" },
      { id: 167, Nombre_Corto: "PK", Nombre: "Pakistán" },
      { id: 168, Nombre_Corto: "PW", Nombre: "Palau" },
      { id: 169, Nombre_Corto: "PS", Nombre: "Palestina" },
      { id: 170, Nombre_Corto: "PA", Nombre: "Panamá" },
      { id: 171, Nombre_Corto: "PG", Nombre: "Papúa Nueva Guinea" },
      { id: 172, Nombre_Corto: "PY", Nombre: "Paraguay" },
      { id: 173, Nombre_Corto: "PE", Nombre: "Perú" },
      { id: 174, Nombre_Corto: "PN", Nombre: "Islas Pitcairn" },
      { id: 175, Nombre_Corto: "PF", Nombre: "Polinesia Francesa" },
      { id: 176, Nombre_Corto: "PL", Nombre: "Polonia" },
      { id: 177, Nombre_Corto: "PT", Nombre: "Portugal" },
      { id: 178, Nombre_Corto: "PR", Nombre: "Puerto Rico" },
      { id: 179, Nombre_Corto: "QA", Nombre: "Qatar" },
      { id: 180, Nombre_Corto: "GB", Nombre: "Reino Unido" },
      { id: 181, Nombre_Corto: "RE", Nombre: "Reunión" },
      { id: 182, Nombre_Corto: "RW", Nombre: "Ruanda" },
      { id: 183, Nombre_Corto: "RO", Nombre: "Rumania" },
      { id: 184, Nombre_Corto: "RU", Nombre: "Rusia" },
      { id: 185, Nombre_Corto: "EH", Nombre: "Sahara Occidental" },
      { id: 186, Nombre_Corto: "SB", Nombre: "Islas Salomón" },
      { id: 187, Nombre_Corto: "WS", Nombre: "Samoa" },
      { id: 188, Nombre_Corto: "AS", Nombre: "Samoa Americana" },
      { id: 189, Nombre_Corto: "KN", Nombre: "San Cristóbal y Nevis" },
      { id: 190, Nombre_Corto: "SM", Nombre: "San Marino" },
      { id: 191, Nombre_Corto: "PM", Nombre: "San Pedro y Miquelón" },
      { id: 192, Nombre_Corto: "VC", Nombre: "San Vicente y las Granadinas" },
      { id: 193, Nombre_Corto: "SH", Nombre: "Santa Helena" },
      { id: 194, Nombre_Corto: "LC", Nombre: "Santa Lucía" },
      { id: 195, Nombre_Corto: "ST", Nombre: "Santo Tomé y Príncipe" },
      { id: 196, Nombre_Corto: "SN", Nombre: "Senegal" },
      { id: 197, Nombre_Corto: "CS", Nombre: "Serbia y Montenegro" },
      { id: 198, Nombre_Corto: "SC", Nombre: "Seychelles" },
      { id: 199, Nombre_Corto: "SL", Nombre: "Sierra Leona" },
      { id: 200, Nombre_Corto: "SG", Nombre: "Singapur" },
      { id: 201, Nombre_Corto: "SY", Nombre: "Siria" },
      { id: 202, Nombre_Corto: "SO", Nombre: "Somalia" },
      { id: 203, Nombre_Corto: "LK", Nombre: "Sri Lanka" },
      { id: 204, Nombre_Corto: "SZ", Nombre: "Suazilandia" },
      { id: 205, Nombre_Corto: "ZA", Nombre: "Sudáfrica" },
      { id: 206, Nombre_Corto: "SD", Nombre: "Sudán" },
      { id: 207, Nombre_Corto: "SE", Nombre: "Suecia" },
      { id: 208, Nombre_Corto: "CH", Nombre: "Suiza" },
      { id: 209, Nombre_Corto: "SR", Nombre: "Surinam" },
      { id: 210, Nombre_Corto: "SJ", Nombre: "Svalbard y Jan Mayen" },
      { id: 211, Nombre_Corto: "TH", Nombre: "Tailandia" },
      { id: 212, Nombre_Corto: "TW", Nombre: "Taiwán" },
      { id: 213, Nombre_Corto: "TZ", Nombre: "Tanzania" },
      { id: 214, Nombre_Corto: "TJ", Nombre: "Tayikistán" },
      {
        id: 215,
        Nombre_Corto: "IO",
        Nombre: "Territorio Británico del Océano Índco",
      },
      {
        id: 216,
        Nombre_Corto: "TF",
        Nombre: "Territorios Australes Franceses",
      },
      { id: 217, Nombre_Corto: "TL", Nombre: "Timor Oriental" },
      { id: 218, Nombre_Corto: "TG", Nombre: "Togo" },
      { id: 219, Nombre_Corto: "TK", Nombre: "Tokelau" },
      { id: 220, Nombre_Corto: "TO", Nombre: "Tonga" },
      { id: 221, Nombre_Corto: "TT", Nombre: "Trinidad y Tobago" },
      { id: 222, Nombre_Corto: "TN", Nombre: "Túnez" },
      { id: 223, Nombre_Corto: "TC", Nombre: "Islas Turcas y Caicos" },
      { id: 224, Nombre_Corto: "TM", Nombre: "Turkmenistán" },
      { id: 225, Nombre_Corto: "TR", Nombre: "Turquía" },
      { id: 226, Nombre_Corto: "TV", Nombre: "Tuvalu" },
      { id: 227, Nombre_Corto: "UA", Nombre: "Ucrania" },
      { id: 228, Nombre_Corto: "UG", Nombre: "Uganda" },
      { id: 229, Nombre_Corto: "UY", Nombre: "Uruguay" },
      { id: 230, Nombre_Corto: "UZ", Nombre: "Uzbekistán" },
      { id: 231, Nombre_Corto: "VU", Nombre: "Vanuatu" },
      { id: 232, Nombre_Corto: "VE", Nombre: "Venezuela" },
      { id: 233, Nombre_Corto: "VN", Nombre: "Vietnam" },
      { id: 234, Nombre_Corto: "VG", Nombre: "Islas Vírgenes Británicas" },
      {
        id: 235,
        Nombre_Corto: "VI",
        Nombre: "Islas Vírgenes de los Estados Unido",
      },
      { id: 236, Nombre_Corto: "WF", Nombre: "Wallis y Futuna" },
      { id: 237, Nombre_Corto: "YE", Nombre: "Yemen" },
      { id: 238, Nombre_Corto: "DJ", Nombre: "Yibuti" },
      { id: 239, Nombre_Corto: "ZM", Nombre: "Zambia" },
      { id: 240, Nombre_Corto: "ZW", Nombre: "Zimbabue" },
    ]);
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */

    await queryInterface.bulkDelete(
      "paises",
      {
        id: {
          [Sequelize.Op.between]: [1, 240],
        },
      },
      {}
    );
  },
};
