"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    queryInterface.bulkInsert("paises", [
      { Nombre_Corto: "AF", Nombre: "Afganistán" },
      { Nombre_Corto: "AX", Nombre: "Islas Gland" },
      { Nombre_Corto: "AL", Nombre: "Albania" },
      { Nombre_Corto: "DE", Nombre: "Alemania" },
      { Nombre_Corto: "AD", Nombre: "Andorra" },
      { Nombre_Corto: "AO", Nombre: "Angola" },
      { Nombre_Corto: "AI", Nombre: "Anguilla" },
      { Nombre_Corto: "AQ", Nombre: "Antártida" },
      { Nombre_Corto: "AG", Nombre: "Antigua y Barbuda" },
      { Nombre_Corto: "AN", Nombre: "Antillas Holandesas" },
      { Nombre_Corto: "SA", Nombre: "Arabia Saudí" },
      { Nombre_Corto: "DZ", Nombre: "Argelia" },
      { Nombre_Corto: "AR", Nombre: "Argentina" },
      { Nombre_Corto: "AM", Nombre: "Armenia" },
      { Nombre_Corto: "AW", Nombre: "Aruba" },
      { Nombre_Corto: "AU", Nombre: "Australia" },
      { Nombre_Corto: "AT", Nombre: "Austria" },
      { Nombre_Corto: "AZ", Nombre: "Azerbaiyán" },
      { Nombre_Corto: "BS", Nombre: "Bahamas" },
      { Nombre_Corto: "BH", Nombre: "Bahréin" },
      { Nombre_Corto: "BD", Nombre: "Bangladesh" },
      { Nombre_Corto: "BB", Nombre: "Barbados" },
      { Nombre_Corto: "BY", Nombre: "Bielorrusia" },
      { Nombre_Corto: "BE", Nombre: "Bélgica" },
      { Nombre_Corto: "BZ", Nombre: "Belice" },
      { Nombre_Corto: "BJ", Nombre: "Benin" },
      { Nombre_Corto: "BM", Nombre: "Bermudas" },
      { Nombre_Corto: "BT", Nombre: "Bhután" },
      { Nombre_Corto: "BO", Nombre: "Bolivia" },
      { Nombre_Corto: "BA", Nombre: "Bosnia y Herzegovina" },
      { Nombre_Corto: "BW", Nombre: "Botsuana" },
      { Nombre_Corto: "BV", Nombre: "Isla Bouvet" },
      { Nombre_Corto: "BR", Nombre: "Brasil" },
      { Nombre_Corto: "BN", Nombre: "Brunéi" },
      { Nombre_Corto: "BG", Nombre: "Bulgaria" },
      { Nombre_Corto: "BF", Nombre: "Burkina Faso" },
      { Nombre_Corto: "BI", Nombre: "Burundi" },
      { Nombre_Corto: "CV", Nombre: "Cabo Verde" },
      { Nombre_Corto: "KY", Nombre: "Islas Caimán" },
      { Nombre_Corto: "KH", Nombre: "Camboya" },
      { Nombre_Corto: "CM", Nombre: "Camerún" },
      { Nombre_Corto: "CA", Nombre: "Canadá" },
      { Nombre_Corto: "CF", Nombre: "República Centroafricana" },
      { Nombre_Corto: "TD", Nombre: "Chad" },
      { Nombre_Corto: "CZ", Nombre: "República Checa" },
      { Nombre_Corto: "CL", Nombre: "Chile" },
      { Nombre_Corto: "CN", Nombre: "China" },
      { Nombre_Corto: "CY", Nombre: "Chipre" },
      { Nombre_Corto: "CX", Nombre: "Isla de Navidad" },
      { Nombre_Corto: "VA", Nombre: "Ciudad del Vaticano" },
      { Nombre_Corto: "CC", Nombre: "Islas Cocos" },
      { Nombre_Corto: "CO", Nombre: "Colombia" },
      { Nombre_Corto: "KM", Nombre: "Comoras" },
      { Nombre_Corto: "CD", Nombre: "República Democrática del Congo" },
      { Nombre_Corto: "CG", Nombre: "Congo" },
      { Nombre_Corto: "CK", Nombre: "Islas Cook" },
      { Nombre_Corto: "KP", Nombre: "Corea del Norte" },
      { Nombre_Corto: "KR", Nombre: "Corea del Sur" },
      { Nombre_Corto: "CI", Nombre: "Costa de Marfil" },
      { Nombre_Corto: "CR", Nombre: "Costa Rica" },
      { Nombre_Corto: "HR", Nombre: "Croacia" },
      { Nombre_Corto: "CU", Nombre: "Cuba" },
      { Nombre_Corto: "DK", Nombre: "Dinamarca" },
      { Nombre_Corto: "DM", Nombre: "Dominica" },
      { Nombre_Corto: "DO", Nombre: "República Dominicana" },
      { Nombre_Corto: "EC", Nombre: "Ecuador" },
      { Nombre_Corto: "EG", Nombre: "Egipto" },
      { Nombre_Corto: "SV", Nombre: "El Salvador" },
      { Nombre_Corto: "AE", Nombre: "Emiratos Árabes Unidos" },
      { Nombre_Corto: "ER", Nombre: "Eritrea" },
      { Nombre_Corto: "SK", Nombre: "Eslovaquia" },
      { Nombre_Corto: "SI", Nombre: "Eslovenia" },
      { Nombre_Corto: "ES", Nombre: "España" },
      { Nombre_Corto: "UM", Nombre: "Islas ultramarinas de Estados Unido" },
      { Nombre_Corto: "US", Nombre: "Estados Unidos" },
      { Nombre_Corto: "EE", Nombre: "Estonia" },
      { Nombre_Corto: "ET", Nombre: "Etiopía" },
      { Nombre_Corto: "FO", Nombre: "Islas Feroe" },
      { Nombre_Corto: "PH", Nombre: "Filipinas" },
      { Nombre_Corto: "FI", Nombre: "Finlandia" },
      { Nombre_Corto: "FJ", Nombre: "Fiyi" },
      { Nombre_Corto: "FR", Nombre: "Francia" },
      { Nombre_Corto: "GA", Nombre: "Gabón" },
      { Nombre_Corto: "GM", Nombre: "Gambia" },
      { Nombre_Corto: "GE", Nombre: "Georgia" },
      {
        Nombre_Corto: "GS",
        Nombre: "Islas Georgias del Sur y Sandwich dl Sur",
      },
      { Nombre_Corto: "GH", Nombre: "Ghana" },
      { Nombre_Corto: "GI", Nombre: "Gibraltar" },
      { Nombre_Corto: "GD", Nombre: "Granada" },
      { Nombre_Corto: "GR", Nombre: "Grecia" },
      { Nombre_Corto: "GL", Nombre: "Groenlandia" },
      { Nombre_Corto: "GP", Nombre: "Guadalupe" },
      { Nombre_Corto: "GU", Nombre: "Guam" },
      { Nombre_Corto: "GT", Nombre: "Guatemala" },
      { Nombre_Corto: "GF", Nombre: "Guayana Francesa" },
      { Nombre_Corto: "GN", Nombre: "Guinea" },
      { Nombre_Corto: "GQ", Nombre: "Guinea Ecuatorial" },
      { Nombre_Corto: "GW", Nombre: "Guinea-Bissau" },
      { Nombre_Corto: "GY", Nombre: "Guyana" },
      { Nombre_Corto: "HT", Nombre: "Haití" },
      { Nombre_Corto: "HM", Nombre: "Islas Heard y McDonald" },
      { Nombre_Corto: "HN", Nombre: "Honduras" },
      { Nombre_Corto: "HK", Nombre: "Hong Kong" },
      { Nombre_Corto: "HU", Nombre: "Hungría" },
      { Nombre_Corto: "IN", Nombre: "India" },
      { Nombre_Corto: "ID", Nombre: "Indonesia" },
      { Nombre_Corto: "IR", Nombre: "Irán" },
      { Nombre_Corto: "IQ", Nombre: "Iraq" },
      { Nombre_Corto: "IE", Nombre: "Irlanda" },
      { Nombre_Corto: "IS", Nombre: "Islandia" },
      { Nombre_Corto: "IL", Nombre: "Israel" },
      { Nombre_Corto: "IT", Nombre: "Italia" },
      { Nombre_Corto: "JM", Nombre: "Jamaica" },
      { Nombre_Corto: "JP", Nombre: "Japón" },
      { Nombre_Corto: "JO", Nombre: "Jordania" },
      { Nombre_Corto: "KZ", Nombre: "Kazajstán" },
      { Nombre_Corto: "KE", Nombre: "Kenia" },
      { Nombre_Corto: "KG", Nombre: "Kirguistán" },
      { Nombre_Corto: "KI", Nombre: "Kiribati" },
      { Nombre_Corto: "KW", Nombre: "Kuwait" },
      { Nombre_Corto: "LA", Nombre: "Laos" },
      { Nombre_Corto: "LS", Nombre: "Lesotho" },
      { Nombre_Corto: "LV", Nombre: "Letonia" },
      { Nombre_Corto: "LB", Nombre: "Líbano" },
      { Nombre_Corto: "LR", Nombre: "Liberia" },
      { Nombre_Corto: "LY", Nombre: "Libia" },
      { Nombre_Corto: "LI", Nombre: "Liechtenstein" },
      { Nombre_Corto: "LT", Nombre: "Lituania" },
      { Nombre_Corto: "LU", Nombre: "Luxemburgo" },
      { Nombre_Corto: "MO", Nombre: "Macao" },
      { Nombre_Corto: "MK", Nombre: "ARY Macedonia" },
      { Nombre_Corto: "MG", Nombre: "Madagascar" },
      { Nombre_Corto: "MY", Nombre: "Malasia" },
      { Nombre_Corto: "MW", Nombre: "Malawi" },
      { Nombre_Corto: "MV", Nombre: "Maldivas" },
      { Nombre_Corto: "ML", Nombre: "Malí" },
      { Nombre_Corto: "MT", Nombre: "Malta" },
      { Nombre_Corto: "FK", Nombre: "Islas Malvinas" },
      { Nombre_Corto: "MP", Nombre: "Islas Marianas del Norte" },
      { Nombre_Corto: "MA", Nombre: "Marruecos" },
      { Nombre_Corto: "MH", Nombre: "Islas Marshall" },
      { Nombre_Corto: "MQ", Nombre: "Martinica" },
      { Nombre_Corto: "MU", Nombre: "Mauricio" },
      { Nombre_Corto: "MR", Nombre: "Mauritania" },
      { Nombre_Corto: "YT", Nombre: "Mayotte" },
      { Nombre_Corto: "MX", Nombre: "México" },
      { Nombre_Corto: "FM", Nombre: "Micronesia" },
      { Nombre_Corto: "MD", Nombre: "Moldavia" },
      { Nombre_Corto: "MC", Nombre: "Mónaco" },
      { Nombre_Corto: "MN", Nombre: "Mongolia" },
      { Nombre_Corto: "MS", Nombre: "Montserrat" },
      { Nombre_Corto: "MZ", Nombre: "Mozambique" },
      { Nombre_Corto: "MM", Nombre: "Myanmar" },
      { Nombre_Corto: "NA", Nombre: "Namibia" },
      { Nombre_Corto: "NR", Nombre: "Nauru" },
      { Nombre_Corto: "NP", Nombre: "Nepal" },
      { Nombre_Corto: "NI", Nombre: "Nicaragua" },
      { Nombre_Corto: "NE", Nombre: "Níger" },
      { Nombre_Corto: "NG", Nombre: "Nigeria" },
      { Nombre_Corto: "NU", Nombre: "Niue" },
      { Nombre_Corto: "NF", Nombre: "Isla Norfolk" },
      { Nombre_Corto: "NO", Nombre: "Noruega" },
      { Nombre_Corto: "NC", Nombre: "Nueva Caledonia" },
      { Nombre_Corto: "NZ", Nombre: "Nueva Zelanda" },
      { Nombre_Corto: "OM", Nombre: "Omán" },
      { Nombre_Corto: "NL", Nombre: "Países Bajos" },
      { Nombre_Corto: "PK", Nombre: "Pakistán" },
      { Nombre_Corto: "PW", Nombre: "Palau" },
      { Nombre_Corto: "PS", Nombre: "Palestina" },
      { Nombre_Corto: "PA", Nombre: "Panamá" },
      { Nombre_Corto: "PG", Nombre: "Papúa Nueva Guinea" },
      { Nombre_Corto: "PY", Nombre: "Paraguay" },
      { Nombre_Corto: "PE", Nombre: "Perú" },
      { Nombre_Corto: "PN", Nombre: "Islas Pitcairn" },
      { Nombre_Corto: "PF", Nombre: "Polinesia Francesa" },
      { Nombre_Corto: "PL", Nombre: "Polonia" },
      { Nombre_Corto: "PT", Nombre: "Portugal" },
      { Nombre_Corto: "PR", Nombre: "Puerto Rico" },
      { Nombre_Corto: "QA", Nombre: "Qatar" },
      { Nombre_Corto: "GB", Nombre: "Reino Unido" },
      { Nombre_Corto: "RE", Nombre: "Reunión" },
      { Nombre_Corto: "RW", Nombre: "Ruanda" },
      { Nombre_Corto: "RO", Nombre: "Rumania" },
      { Nombre_Corto: "RU", Nombre: "Rusia" },
      { Nombre_Corto: "EH", Nombre: "Sahara Occidental" },
      { Nombre_Corto: "SB", Nombre: "Islas Salomón" },
      { Nombre_Corto: "WS", Nombre: "Samoa" },
      { Nombre_Corto: "AS", Nombre: "Samoa Americana" },
      { Nombre_Corto: "KN", Nombre: "San Cristóbal y Nevis" },
      { Nombre_Corto: "SM", Nombre: "San Marino" },
      { Nombre_Corto: "PM", Nombre: "San Pedro y Miquelón" },
      { Nombre_Corto: "VC", Nombre: "San Vicente y las Granadinas" },
      { Nombre_Corto: "SH", Nombre: "Santa Helena" },
      { Nombre_Corto: "LC", Nombre: "Santa Lucía" },
      { Nombre_Corto: "ST", Nombre: "Santo Tomé y Príncipe" },
      { Nombre_Corto: "SN", Nombre: "Senegal" },
      { Nombre_Corto: "CS", Nombre: "Serbia y Montenegro" },
      { Nombre_Corto: "SC", Nombre: "Seychelles" },
      { Nombre_Corto: "SL", Nombre: "Sierra Leona" },
      { Nombre_Corto: "SG", Nombre: "Singapur" },
      { Nombre_Corto: "SY", Nombre: "Siria" },
      { Nombre_Corto: "SO", Nombre: "Somalia" },
      { Nombre_Corto: "LK", Nombre: "Sri Lanka" },
      { Nombre_Corto: "SZ", Nombre: "Suazilandia" },
      { Nombre_Corto: "ZA", Nombre: "Sudáfrica" },
      { Nombre_Corto: "SD", Nombre: "Sudán" },
      { Nombre_Corto: "SE", Nombre: "Suecia" },
      { Nombre_Corto: "CH", Nombre: "Suiza" },
      { Nombre_Corto: "SR", Nombre: "Surinam" },
      { Nombre_Corto: "SJ", Nombre: "Svalbard y Jan Mayen" },
      { Nombre_Corto: "TH", Nombre: "Tailandia" },
      { Nombre_Corto: "TW", Nombre: "Taiwán" },
      { Nombre_Corto: "TZ", Nombre: "Tanzania" },
      { Nombre_Corto: "TJ", Nombre: "Tayikistán" },
      { Nombre_Corto: "IO", Nombre: "Territorio Británico del Océano Índco" },
      { Nombre_Corto: "TF", Nombre: "Territorios Australes Franceses" },
      { Nombre_Corto: "TL", Nombre: "Timor Oriental" },
      { Nombre_Corto: "TG", Nombre: "Togo" },
      { Nombre_Corto: "TK", Nombre: "Tokelau" },
      { Nombre_Corto: "TO", Nombre: "Tonga" },
      { Nombre_Corto: "TT", Nombre: "Trinidad y Tobago" },
      { Nombre_Corto: "TN", Nombre: "Túnez" },
      { Nombre_Corto: "TC", Nombre: "Islas Turcas y Caicos" },
      { Nombre_Corto: "TM", Nombre: "Turkmenistán" },
      { Nombre_Corto: "TR", Nombre: "Turquía" },
      { Nombre_Corto: "TV", Nombre: "Tuvalu" },
      { Nombre_Corto: "UA", Nombre: "Ucrania" },
      { Nombre_Corto: "UG", Nombre: "Uganda" },
      { Nombre_Corto: "UY", Nombre: "Uruguay" },
      { Nombre_Corto: "UZ", Nombre: "Uzbekistán" },
      { Nombre_Corto: "VU", Nombre: "Vanuatu" },
      { Nombre_Corto: "VE", Nombre: "Venezuela" },
      { Nombre_Corto: "VN", Nombre: "Vietnam" },
      { Nombre_Corto: "VG", Nombre: "Islas Vírgenes Británicas" },
      { Nombre_Corto: "VI", Nombre: "Islas Vírgenes de los Estados Unido" },
      { Nombre_Corto: "WF", Nombre: "Wallis y Futuna" },
      { Nombre_Corto: "YE", Nombre: "Yemen" },
      { Nombre_Corto: "DJ", Nombre: "Yibuti" },
      { Nombre_Corto: "ZM", Nombre: "Zambia" },
      { Nombre_Corto: "ZW", Nombre: "Zimbabue" },
    ]);
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */

    await queryInterface.bulkDelete("paises", null, {});
  },
};
