"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    queryInterface.bulkInsert("country", [
      { id: 1, shortName: "AF", name: "Afganistán" },
      { id: 2, shortName: "AX", name: "Islas Gland" },
      { id: 3, shortName: "AL", name: "Albania" },
      { id: 4, shortName: "DE", name: "Alemania" },
      { id: 5, shortName: "AD", name: "Andorra" },
      { id: 6, shortName: "AO", name: "Angola" },
      { id: 7, shortName: "AI", name: "Anguilla" },
      { id: 8, shortName: "AQ", name: "Antártida" },
      { id: 9, shortName: "AG", name: "Antigua y Barbuda" },
      { id: 10, shortName: "AN", name: "Antillas Holandesas" },
      { id: 11, shortName: "SA", name: "Arabia Saudí" },
      { id: 12, shortName: "DZ", name: "Argelia" },
      { id: 13, shortName: "AR", name: "Argentina" },
      { id: 14, shortName: "AM", name: "Armenia" },
      { id: 15, shortName: "AW", name: "Aruba" },
      { id: 16, shortName: "AU", name: "Australia" },
      { id: 17, shortName: "AT", name: "Austria" },
      { id: 18, shortName: "AZ", name: "Azerbaiyán" },
      { id: 19, shortName: "BS", name: "Bahamas" },
      { id: 20, shortName: "BH", name: "Bahréin" },
      { id: 21, shortName: "BD", name: "Bangladesh" },
      { id: 22, shortName: "BB", name: "Barbados" },
      { id: 23, shortName: "BY", name: "Bielorrusia" },
      { id: 24, shortName: "BE", name: "Bélgica" },
      { id: 25, shortName: "BZ", name: "Belice" },
      { id: 26, shortName: "BJ", name: "Benin" },
      { id: 27, shortName: "BM", name: "Bermudas" },
      { id: 28, shortName: "BT", name: "Bhután" },
      { id: 29, shortName: "BO", name: "Bolivia" },
      { id: 30, shortName: "BA", name: "Bosnia y Herzegovina" },
      { id: 31, shortName: "BW", name: "Botsuana" },
      { id: 32, shortName: "BV", name: "Isla Bouvet" },
      { id: 33, shortName: "BR", name: "Brasil" },
      { id: 34, shortName: "BN", name: "Brunéi" },
      { id: 35, shortName: "BG", name: "Bulgaria" },
      { id: 36, shortName: "BF", name: "Burkina Faso" },
      { id: 37, shortName: "BI", name: "Burundi" },
      { id: 38, shortName: "CV", name: "Cabo Verde" },
      { id: 39, shortName: "KY", name: "Islas Caimán" },
      { id: 40, shortName: "KH", name: "Camboya" },
      { id: 41, shortName: "CM", name: "Camerún" },
      { id: 42, shortName: "CA", name: "Canadá" },
      { id: 43, shortName: "CF", name: "República Centroafricana" },
      { id: 44, shortName: "TD", name: "Chad" },
      { id: 45, shortName: "CZ", name: "República Checa" },
      { id: 46, shortName: "CL", name: "Chile" },
      { id: 47, shortName: "CN", name: "China" },
      { id: 48, shortName: "CY", name: "Chipre" },
      { id: 49, shortName: "CX", name: "Isla de Navidad" },
      { id: 50, shortName: "VA", name: "Ciudad del Vaticano" },
      { id: 51, shortName: "CC", name: "Islas Cocos" },
      { id: 52, shortName: "CO", name: "Colombia" },
      { id: 53, shortName: "KM", name: "Comoras" },
      { id: 54, shortName: "CD", name: "República Democrática del Congo" },
      { id: 55, shortName: "CG", name: "Congo" },
      { id: 56, shortName: "CK", name: "Islas Cook" },
      { id: 57, shortName: "KP", name: "Corea del Norte" },
      { id: 58, shortName: "KR", name: "Corea del Sur" },
      { id: 59, shortName: "CI", name: "Costa de Marfil" },
      { id: 60, shortName: "CR", name: "Costa Rica" },
      { id: 61, shortName: "HR", name: "Croacia" },
      { id: 62, shortName: "CU", name: "Cuba" },
      { id: 63, shortName: "DK", name: "Dinamarca" },
      { id: 64, shortName: "DM", name: "Dominica" },
      { id: 65, shortName: "DO", name: "República Dominicana" },
      { id: 66, shortName: "EC", name: "Ecuador" },
      { id: 67, shortName: "EG", name: "Egipto" },
      { id: 68, shortName: "SV", name: "El Salvador" },
      { id: 69, shortName: "AE", name: "Emiratos Árabes Unidos" },
      { id: 70, shortName: "ER", name: "Eritrea" },
      { id: 71, shortName: "SK", name: "Eslovaquia" },
      { id: 72, shortName: "SI", name: "Eslovenia" },
      { id: 73, shortName: "ES", name: "España" },
      {
        id: 74,
        shortName: "UM",
        name: "Islas ultramarinas de Estados Unido",
      },
      { id: 75, shortName: "US", name: "Estados Unidos" },
      { id: 76, shortName: "EE", name: "Estonia" },
      { id: 77, shortName: "ET", name: "Etiopía" },
      { id: 78, shortName: "FO", name: "Islas Feroe" },
      { id: 79, shortName: "PH", name: "Filipinas" },
      { id: 80, shortName: "FI", name: "Finlandia" },
      { id: 81, shortName: "FJ", name: "Fiyi" },
      { id: 82, shortName: "FR", name: "Francia" },
      { id: 83, shortName: "GA", name: "Gabón" },
      { id: 84, shortName: "GM", name: "Gambia" },
      { id: 85, shortName: "GE", name: "Georgia" },
      {
        id: 86,
        shortName: "GS",
        name: "Islas Georgias del Sur y Sandwich dl Sur",
      },
      { id: 87, shortName: "GH", name: "Ghana" },
      { id: 88, shortName: "GI", name: "Gibraltar" },
      { id: 89, shortName: "GD", name: "Granada" },
      { id: 90, shortName: "GR", name: "Grecia" },
      { id: 91, shortName: "GL", name: "Groenlandia" },
      { id: 92, shortName: "GP", name: "Guadalupe" },
      { id: 93, shortName: "GU", name: "Guam" },
      { id: 94, shortName: "GT", name: "Guatemala" },
      { id: 95, shortName: "GF", name: "Guayana Francesa" },
      { id: 96, shortName: "GN", name: "Guinea" },
      { id: 97, shortName: "GQ", name: "Guinea Ecuatorial" },
      { id: 98, shortName: "GW", name: "Guinea-Bissau" },
      { id: 99, shortName: "GY", name: "Guyana" },
      { id: 100, shortName: "HT", name: "Haití" },
      { id: 101, shortName: "HM", name: "Islas Heard y McDonald" },
      { id: 102, shortName: "HN", name: "Honduras" },
      { id: 103, shortName: "HK", name: "Hong Kong" },
      { id: 104, shortName: "HU", name: "Hungría" },
      { id: 105, shortName: "IN", name: "India" },
      { id: 106, shortName: "ID", name: "Indonesia" },
      { id: 107, shortName: "IR", name: "Irán" },
      { id: 108, shortName: "IQ", name: "Iraq" },
      { id: 109, shortName: "IE", name: "Irlanda" },
      { id: 110, shortName: "IS", name: "Islandia" },
      { id: 111, shortName: "IL", name: "Israel" },
      { id: 112, shortName: "IT", name: "Italia" },
      { id: 113, shortName: "JM", name: "Jamaica" },
      { id: 114, shortName: "JP", name: "Japón" },
      { id: 115, shortName: "JO", name: "Jordania" },
      { id: 116, shortName: "KZ", name: "Kazajstán" },
      { id: 117, shortName: "KE", name: "Kenia" },
      { id: 118, shortName: "KG", name: "Kirguistán" },
      { id: 119, shortName: "KI", name: "Kiribati" },
      { id: 120, shortName: "KW", name: "Kuwait" },
      { id: 121, shortName: "LA", name: "Laos" },
      { id: 122, shortName: "LS", name: "Lesotho" },
      { id: 123, shortName: "LV", name: "Letonia" },
      { id: 124, shortName: "LB", name: "Líbano" },
      { id: 125, shortName: "LR", name: "Liberia" },
      { id: 126, shortName: "LY", name: "Libia" },
      { id: 127, shortName: "LI", name: "Liechtenstein" },
      { id: 128, shortName: "LT", name: "Lituania" },
      { id: 129, shortName: "LU", name: "Luxemburgo" },
      { id: 130, shortName: "MO", name: "Macao" },
      { id: 131, shortName: "MK", name: "ARY Macedonia" },
      { id: 132, shortName: "MG", name: "Madagascar" },
      { id: 133, shortName: "MY", name: "Malasia" },
      { id: 134, shortName: "MW", name: "Malawi" },
      { id: 135, shortName: "MV", name: "Maldivas" },
      { id: 136, shortName: "ML", name: "Malí" },
      { id: 137, shortName: "MT", name: "Malta" },
      { id: 138, shortName: "FK", name: "Islas Malvinas" },
      { id: 139, shortName: "MP", name: "Islas Marianas del Norte" },
      { id: 140, shortName: "MA", name: "Marruecos" },
      { id: 141, shortName: "MH", name: "Islas Marshall" },
      { id: 142, shortName: "MQ", name: "Martinica" },
      { id: 143, shortName: "MU", name: "Mauricio" },
      { id: 144, shortName: "MR", name: "Mauritania" },
      { id: 145, shortName: "YT", name: "Mayotte" },
      { id: 146, shortName: "MX", name: "México" },
      { id: 147, shortName: "FM", name: "Micronesia" },
      { id: 148, shortName: "MD", name: "Moldavia" },
      { id: 149, shortName: "MC", name: "Mónaco" },
      { id: 150, shortName: "MN", name: "Mongolia" },
      { id: 151, shortName: "MS", name: "Montserrat" },
      { id: 152, shortName: "MZ", name: "Mozambique" },
      { id: 153, shortName: "MM", name: "Myanmar" },
      { id: 154, shortName: "NA", name: "Namibia" },
      { id: 155, shortName: "NR", name: "Nauru" },
      { id: 156, shortName: "NP", name: "Nepal" },
      { id: 157, shortName: "NI", name: "Nicaragua" },
      { id: 158, shortName: "NE", name: "Níger" },
      { id: 159, shortName: "NG", name: "Nigeria" },
      { id: 160, shortName: "NU", name: "Niue" },
      { id: 161, shortName: "NF", name: "Isla Norfolk" },
      { id: 162, shortName: "NO", name: "Noruega" },
      { id: 163, shortName: "NC", name: "Nueva Caledonia" },
      { id: 164, shortName: "NZ", name: "Nueva Zelanda" },
      { id: 165, shortName: "OM", name: "Omán" },
      { id: 166, shortName: "NL", name: "Países Bajos" },
      { id: 167, shortName: "PK", name: "Pakistán" },
      { id: 168, shortName: "PW", name: "Palau" },
      { id: 169, shortName: "PS", name: "Palestina" },
      { id: 170, shortName: "PA", name: "Panamá" },
      { id: 171, shortName: "PG", name: "Papúa Nueva Guinea" },
      { id: 172, shortName: "PY", name: "Paraguay" },
      { id: 173, shortName: "PE", name: "Perú" },
      { id: 174, shortName: "PN", name: "Islas Pitcairn" },
      { id: 175, shortName: "PF", name: "Polinesia Francesa" },
      { id: 176, shortName: "PL", name: "Polonia" },
      { id: 177, shortName: "PT", name: "Portugal" },
      { id: 178, shortName: "PR", name: "Puerto Rico" },
      { id: 179, shortName: "QA", name: "Qatar" },
      { id: 180, shortName: "GB", name: "Reino Unido" },
      { id: 181, shortName: "RE", name: "Reunión" },
      { id: 182, shortName: "RW", name: "Ruanda" },
      { id: 183, shortName: "RO", name: "Rumania" },
      { id: 184, shortName: "RU", name: "Rusia" },
      { id: 185, shortName: "EH", name: "Sahara Occidental" },
      { id: 186, shortName: "SB", name: "Islas Salomón" },
      { id: 187, shortName: "WS", name: "Samoa" },
      { id: 188, shortName: "AS", name: "Samoa Americana" },
      { id: 189, shortName: "KN", name: "San Cristóbal y Nevis" },
      { id: 190, shortName: "SM", name: "San Marino" },
      { id: 191, shortName: "PM", name: "San Pedro y Miquelón" },
      { id: 192, shortName: "VC", name: "San Vicente y las Granadinas" },
      { id: 193, shortName: "SH", name: "Santa Helena" },
      { id: 194, shortName: "LC", name: "Santa Lucía" },
      { id: 195, shortName: "ST", name: "Santo Tomé y Príncipe" },
      { id: 196, shortName: "SN", name: "Senegal" },
      { id: 197, shortName: "CS", name: "Serbia y Montenegro" },
      { id: 198, shortName: "SC", name: "Seychelles" },
      { id: 199, shortName: "SL", name: "Sierra Leona" },
      { id: 200, shortName: "SG", name: "Singapur" },
      { id: 201, shortName: "SY", name: "Siria" },
      { id: 202, shortName: "SO", name: "Somalia" },
      { id: 203, shortName: "LK", name: "Sri Lanka" },
      { id: 204, shortName: "SZ", name: "Suazilandia" },
      { id: 205, shortName: "ZA", name: "Sudáfrica" },
      { id: 206, shortName: "SD", name: "Sudán" },
      { id: 207, shortName: "SE", name: "Suecia" },
      { id: 208, shortName: "CH", name: "Suiza" },
      { id: 209, shortName: "SR", name: "Surinam" },
      { id: 210, shortName: "SJ", name: "Svalbard y Jan Mayen" },
      { id: 211, shortName: "TH", name: "Tailandia" },
      { id: 212, shortName: "TW", name: "Taiwán" },
      { id: 213, shortName: "TZ", name: "Tanzania" },
      { id: 214, shortName: "TJ", name: "Tayikistán" },
      {
        id: 215,
        shortName: "IO",
        name: "Territorio Británico del Océano Índco",
      },
      {
        id: 216,
        shortName: "TF",
        name: "Territorios Australes Franceses",
      },
      { id: 217, shortName: "TL", name: "Timor Oriental" },
      { id: 218, shortName: "TG", name: "Togo" },
      { id: 219, shortName: "TK", name: "Tokelau" },
      { id: 220, shortName: "TO", name: "Tonga" },
      { id: 221, shortName: "TT", name: "Trinidad y Tobago" },
      { id: 222, shortName: "TN", name: "Túnez" },
      { id: 223, shortName: "TC", name: "Islas Turcas y Caicos" },
      { id: 224, shortName: "TM", name: "Turkmenistán" },
      { id: 225, shortName: "TR", name: "Turquía" },
      { id: 226, shortName: "TV", name: "Tuvalu" },
      { id: 227, shortName: "UA", name: "Ucrania" },
      { id: 228, shortName: "UG", name: "Uganda" },
      { id: 229, shortName: "UY", name: "Uruguay" },
      { id: 230, shortName: "UZ", name: "Uzbekistán" },
      { id: 231, shortName: "VU", name: "Vanuatu" },
      { id: 232, shortName: "VE", name: "Venezuela" },
      { id: 233, shortName: "VN", name: "Vietnam" },
      { id: 234, shortName: "VG", name: "Islas Vírgenes Británicas" },
      {
        id: 235,
        shortName: "VI",
        name: "Islas Vírgenes de los Estados Unido",
      },
      { id: 236, shortName: "WF", name: "Wallis y Futuna" },
      { id: 237, shortName: "YE", name: "Yemen" },
      { id: 238, shortName: "DJ", name: "Yibuti" },
      { id: 239, shortName: "ZM", name: "Zambia" },
      { id: 240, shortName: "ZW", name: "Zimbabue" },
    ]);
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */

    await queryInterface.bulkDelete(
      "country",
      {
        id: {
          [Sequelize.Op.between]: [1, 240],
        },
      },
      {}
    );
  },
};
