name: Deveploment deploy
on:
  push:
    branches:
      - dev*
      - ci-cd*

jobs:
  build:
    name: Run command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: dev
      - name: Package source code
        run: tar -cvzf dev-${{ github.sha }}.tar.gz -C dev .
      - name: Copy file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY }}
          source: "dev-${{ github.sha }}.tar.gz"
          target: "development"
      - name: Unpack source code & setup environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_DEV }}
          username: ${{ secrets.USER_DEV }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd development/utils
            ./down.sh
            cd
            mv -f development/code development/code_old
            mkdir -p development/code
            tar -xvzf development/dev-${{ github.sha }}.tar.gz -C development/code
            rm -f development/development-*.tar.gz
            cd development/utils
            ./rebuild.sh
            ./start.sh
