name: Production deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Run command
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          path: production
          submodules: "recursive"
      - name: Package source code
        run: tar -cvzf production-${{ github.sha }}.tar.gz -C production .
      - name: Copy file via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "production-${{ github.sha }}.tar.gz"
          target: "production"
      - name: Unpack source code & setup environment
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd production/utils
            ./down.sh
            cd
            mv -f production/code production/code_old
            mkdir -p production/code
            tar -xvzf production/production-${{ github.sha }}.tar.gz -C production/code
            rm -f production/production-*.tar.gz
            cd production/utils
            ./rebuild.sh
            ./start.sh
